package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/upwindsecurity/terraform-provider-upwind/internal/client"
)

var (
	_ datasource.DataSource              = &StoryDataSource{}
	_ datasource.DataSourceWithConfigure = &StoryDataSource{}
)

// NewStoryDataSource is the factory registered with the provider.
func NewStoryDataSource() datasource.DataSource {
	return &StoryDataSource{}
}

// StoryDataSource implements the upwind_threat_story data source: one story by id.
//
// Stories are platform-generated - there is no create endpoint - so they can only
// ever be read, never managed as a resource.
type StoryDataSource struct {
	client *client.Client
}

type storyDataSourceModel struct {
	ID           types.String `tfsdk:"id"`
	Title        types.String `tfsdk:"title"`
	Description  types.String `tfsdk:"description"`
	Severity     types.String `tfsdk:"severity"`
	Status       types.String `tfsdk:"status"`
	StatusReason types.String `tfsdk:"status_reason"`
	DetectionIDs types.List   `tfsdk:"detection_ids"`
	CreateTime   types.String `tfsdk:"create_time"`
	UpdateTime   types.String `tfsdk:"update_time"`
}

func (d *StoryDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_threat_story"
}

func (d *StoryDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Reads a single Upwind threat story by ID. Stories are generated by the platform and cannot be managed as a resource.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Required:            true,
				MarkdownDescription: "Unique identifier of the story to read.",
			},
			"title": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Story title.",
			},
			// Only the singular GET returns these two; the collection endpoints omit
			// them, which is why upwind_threat_stories leaves them out entirely.
			"description": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Detailed description of the story. Returned only by this single-story lookup, not by `upwind_threat_stories`.",
			},
			"status_reason": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Reason the story was archived. Null if the story is open or was archived without a reason.",
			},
			"severity": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Severity: `CRITICAL`, `HIGH`, `MEDIUM`, `LOW`, or `INFO`. Note the uppercase, which differs from the lowercase severities used by threat policies.",
			},
			"status": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Status: `OPEN` or `ARCHIVED`.",
			},
			"detection_ids": schema.ListAttribute{
				Computed:            true,
				ElementType:         types.StringType,
				MarkdownDescription: "IDs of the detections that make up this story.",
			},
			"create_time": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "ISO8601 timestamp when the story was created.",
			},
			"update_time": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "ISO8601 timestamp when the story was last updated.",
			},
		},
	}
}

func (d *StoryDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected provider data",
			fmt.Sprintf("expected *client.Client, got %T. This is a provider bug.", req.ProviderData),
		)
		return
	}
	d.client = c
}

func (d *StoryDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var config storyDataSourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &config)...)
	if resp.Diagnostics.HasError() {
		return
	}

	story, err := d.client.GetStory(ctx, config.ID.ValueString())
	if err != nil {
		// A data source pointing at a missing object is a config error, not silent
		// drift: unlike a resource there is no state to remove, so fail loudly.
		if client.IsNotFound(err) {
			resp.Diagnostics.AddError(
				"Threat story not found",
				fmt.Sprintf("no story with ID %q exists in this organization.", config.ID.ValueString()),
			)
			return
		}
		resp.Diagnostics.AddError("Error reading threat story", err.Error())
		return
	}

	detectionIDs, diags := types.ListValueFrom(ctx, types.StringType, story.DetectionIDs)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, storyDataSourceModel{
		ID:           types.StringValue(story.ID),
		Title:        types.StringValue(story.Title),
		Description:  types.StringValue(story.Description),
		Severity:     types.StringValue(story.Severity),
		Status:       types.StringValue(story.Status),
		StatusReason: preserveNull(story.StatusReason, types.StringNull()),
		DetectionIDs: detectionIDs,
		CreateTime:   types.StringValue(story.CreateTime),
		UpdateTime:   types.StringValue(story.UpdateTime),
	})...)
}
